return {
	name = "Meadow",
	description = "A tranquil world of rolling green hills and warm sunlight. Gentle terrain with low elevation makes for smooth cruising.",
	accentColor = Color3.fromRGB(140, 210, 100),
	planetColor = Color3.fromRGB(80, 180, 60),
	tagline = "Rolling green hills",

	material = Enum.Material.Grass,
	amp = 12,
	noiseScale = 0.007,
	seed = 42,

	terrain = {
		octaves = 5,
		lacunarity = 2,
		gain = 0.48,
		ridgeWeight = 0.12,
		warpAmp = 14,
		verticalStuds = 128,
		caveEnabled = true,
		caveThreshold = 0.42,
		caveScale = 0.032,
		caveSkinVoxels = 2,
		heightScale = 1.05,
	},

	atmosphere = {
		fogColor = Color3.fromRGB(140, 170, 200),
		decay = Color3.fromRGB(180, 160, 130),
		density = 0.15, haze = 1, glare = 0.05,
	},
	bloom = { intensity = 0.03, size = 12, threshold = 1.2 },
	cc = {
		tint = Color3.fromRGB(240, 235, 225),
		brightness = 0.02, contrast = 0.08, saturation = 0.15,
	},
	lighting = {
		clockTime = 14.5,
		brightness = 2,
		ambient = Color3.fromRGB(100, 110, 120),
		outdoorAmbient = Color3.fromRGB(90, 100, 110),
		fogColor = Color3.fromRGB(140, 170, 200),
		fogStart = 150,
		fogEnd = 800,
		envDiffuse = 0.5,
		envSpecular = 0.3,
		globalShadows = true,
	},

	orbit = { radius = 0.18, angle = math.rad(90) },

	elements = {
		{
			type = "lsystem",
			density = 0.012,
			cell = 14,
			minScale = 1.4,
			maxScale = 2.6,
			rule = {
				name = "MeadowMonolith",
				axiom = "F",
				rules = { F = "[+FL][-FL][^FL]F" },
				iterations = 2,
				angle = 32,
				segmentLength = 4.5,
				segmentThickness = 1.8,
				lengthDecay = 0.68,
				thicknessDecay = 0.6,
				material = Enum.Material.Grass,
				color = Color3.fromRGB(55, 140, 45),
				leafEnabled = true,
				leafSize = 3.5,
				leafColor = Color3.fromRGB(90, 200, 70),
			},
		},
		{
			type = "lsystem",
			density = 0.015,
			cell = 14,
			minScale = 2.0,
			maxScale = 3.5,
			rule = {
				name = "GiantTree",
				axiom = "F",
				rules = { F = "FF+[+F-FL]-[-F+FL]" },
				iterations = 4,
				angle = 22,
				segmentLength = 6,
				segmentThickness = 2.8,
				lengthDecay = 0.72,
				thicknessDecay = 0.65,
				material = Enum.Material.Wood,
				color = Color3.fromRGB(90, 65, 40),
				leafEnabled = true,
				leafSize = 4.5,
				leafColor = Color3.fromRGB(120, 210, 90),
			},
		},
		{
			type = "simple",
			name = "MossyMonolith",
			density = 0.012,
			cell = 12,
			sizeMin = Vector3.new(5, 8, 5),
			sizeMax = Vector3.new(10, 18, 10),
			material = Enum.Material.Rock,
			color = Color3.fromRGB(75, 90, 65),
		},
		{
			type = "simple",
			name = "Boulder",
			density = 0.01,
			cell = 12,
			shape = "Ball",
			sizeMin = Vector3.new(4, 3, 4),
			sizeMax = Vector3.new(12, 8, 12),
			material = Enum.Material.Rock,
			color = Color3.fromRGB(95, 95, 100),
		},
	},
}
