[package]
name = "arin3/roblox-knit-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.7"
Signal = "sleitnick/signal@2.0.1"
Trove = "sleitnick/trove@1.2.0"	
TableUtil = "sleitnick/table-util@1.2.1"
iris = "michael-48/iris@2.2.0"
timer = "sleitnick/timer@1.1.2"
imgizmo = "jakeywastaken/imgizmo@^3.5.0"
Input = "sleitnick/input@2.3.0"
Shake = "sleitnick/shake@1.1.0"	
PID = "sleitnick/pid@2.1.0"