-- Services/IslandGridService.lua
-- Builds a grid of islands, connects them with bridges, and places a thin "waypoint zone" plate on each bridge.
-- Waypoint voxels (spacing/size/etc.) are GENERATED by WaypointService from those plates.
-- Registers:
--  - WaypointService producer for "waypointZone" -> outputs "waypointPart"
--  - WaypointService index for "waypointPart" scoped to this container
--  - NPC_SpawnZoneService for "waypointZone" (ZonePlus-backed spawn points)

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Packages          = ReplicatedStorage:WaitForChild("Packages")
local Knit              = require(Packages.Knit)
local CollectionService = game:GetService("CollectionService")

local Prefabs           = ReplicatedStorage:WaitForChild("Prefabs")

-- Tags
local WAYPOINT_ZONE_TAG  = "waypointZone"  -- applied to bridge-top plates (producer input)
local WAYPOINT_PART_TAG  = "waypointPart"  -- produced waypoint voxels (query output)

local IslandGridService = Knit.CreateService {
    Name = "IslandGridService",
    Client = {},
}

-- ====== CONFIG ======
local GRID_ROWS     = 2
local GRID_COLS     = 2
local GRID_SPACING  = Vector3.new(150, 0, 150)
local START_CFRAME  = CFrame.new(0, 0, 0)

-- Bridge geometry
local BRIDGE_THICKNESS            = Vector3.new(10, 5, 15) -- Y = 5
local BRIDGE_LENGTH               = 53.487
local BRIDGE_Y                    = 61.342

-- Waypoint zone plate (sits ON TOP of each bridge)
local WAYPOINT_PLATE_THICKNESS    = 1
local WAYPOINT_PLATE_TRANSPARENCY = 0.6
local WAYPOINT_PLATE_COLOR        = Color3.fromRGB(0, 170, 255)
local WAYPOINT_PLATE_MATERIAL     = Enum.Material.SmoothPlastic

-- ====== HELPERS ======
local function getIslandPrefab()
    local island = Prefabs:FindFirstChild("island") or Prefabs:FindFirstChild("Island")
    assert(island and island:IsA("Model"), "Island prefab Model not found in Prefabs.")
    return island
end

local function ensurePrimaryPart(m: Model)
    if m.PrimaryPart and m.PrimaryPart:IsA("BasePart") then
        return m.PrimaryPart
    end
    local candidate = m:FindFirstChild("Primary") or m:FindFirstChild("PrimaryPart")
    if candidate and candidate:IsA("BasePart") then
        m.PrimaryPart = candidate
        return candidate
    end
    for _, d in ipairs(m:GetDescendants()) do
        if d:IsA("BasePart") then
            m.PrimaryPart = d
            return d
        end
    end
    error("Island model has no BasePart to set as PrimaryPart.")
end

local function placeModelAt(model: Model, cf: CFrame)
    ensurePrimaryPart(model)
    model:PivotTo(cf)
end

-- Create the main bridge between two parts and also a thin "waypoint zone" plate on top, tagged.
local function createBridgeAndWaypointZoneBetween(partA: BasePart, partB: BasePart, parent: Instance)
    -- Compute bridge placement/orientation
    local midpoint = (partA.Position + partB.Position) / 2
    midpoint = Vector3.new(midpoint.X, BRIDGE_Y, midpoint.Z)
    local lookAt    = CFrame.lookAt(midpoint, Vector3.new(partB.Position.X, BRIDGE_Y, partB.Position.Z))
    local yawAligned = lookAt * CFrame.Angles(0, math.pi/2, 0) -- keep prior 90° rotation

    -- Main bridge
    local bridge = Instance.new("Part")
    bridge.Name = "Bridge"
    bridge.Anchored = true
    bridge.Size = Vector3.new(BRIDGE_LENGTH, BRIDGE_THICKNESS.Y, BRIDGE_THICKNESS.Z)
    bridge.CFrame = yawAligned
    bridge.Color = Color3.fromRGB(125, 125, 125)
    bridge.Material = Enum.Material.WoodPlanks
    bridge.Parent = parent

    -- Waypoint zone plate sitting ON TOP of the bridge
    local plate = Instance.new("Part")
    plate.Name = "BridgeWaypointZone"
    plate.Anchored = true
    plate.Material = WAYPOINT_PLATE_MATERIAL
    plate.Color = WAYPOINT_PLATE_COLOR
    plate.Transparency = WAYPOINT_PLATE_TRANSPARENCY
    plate.CanCollide = false
    plate.Size = Vector3.new(bridge.Size.X, WAYPOINT_PLATE_THICKNESS, bridge.Size.Z)
    -- place at local +Y offset: (bridge.Y/2 + plate.Y/2)
    local yOffset = (bridge.Size.Y * 0.5) + (plate.Size.Y * 0.5)
    plate.CFrame = bridge.CFrame * CFrame.new(0, yOffset, 0)
    plate.Parent = parent

    -- Tag the top plate so WaypointService can generate voxels on it
    CollectionService:AddTag(plate, WAYPOINT_ZONE_TAG)

    return bridge, plate
end

-- ====== API ======
function IslandGridService:SpawnIslandGrid(rows: number, cols: number, spacing: Vector3, startCf: CFrame, parent: Instance?)
    rows    = math.max(1, rows or GRID_ROWS)
    cols    = math.max(1, cols or GRID_COLS)
    spacing = spacing or GRID_SPACING
    startCf = startCf or START_CFRAME
    parent  = parent or workspace

    local islandPrefab = getIslandPrefab()

    -- Container
    local container = Instance.new("Folder")
    container.Name = "IslandGrid"
    container.Parent = parent

    local islands = {}
    local bridgesFolder = Instance.new("Folder"); bridgesFolder.Name = "Bridges";      bridgesFolder.Parent = container

    -- Spawn islands
    for r = 0, rows - 1 do
        islands[r] = {}
        for c = 0, cols - 1 do
            local island = islandPrefab:Clone()
            island.Name = string.format("Island_r%d_c%d", r + 1, c + 1)
            island.Parent = container

            local offset = Vector3.new(c * spacing.X, 0, r * spacing.Z)
            local cf = startCf + offset
            placeModelAt(island, cf)

            islands[r][c] = island
        end
    end

    -- Bridges + waypoint plates
    for r = 0, rows - 1 do
        for c = 0, cols - 1 do
            local currentIsland  = islands[r][c]
            local currentPrimary = ensurePrimaryPart(currentIsland)

            if c < cols - 1 then
                local rightIsland  = islands[r][c + 1]
                local rightPrimary = ensurePrimaryPart(rightIsland)
                createBridgeAndWaypointZoneBetween(currentPrimary, rightPrimary, bridgesFolder)
            end
            if r < rows - 1 then
                local bottomIsland  = islands[r + 1][c]
                local bottomPrimary = ensurePrimaryPart(bottomIsland)
                createBridgeAndWaypointZoneBetween(currentPrimary, bottomPrimary, bridgesFolder)
            end
        end
    end

    -- === Register with other services ===
    local WaypointService      = Knit.GetService("WaypointService")
    local NPC_SpawnZoneService = Knit.GetService("NPC_SpawnZoneService")

    -- 1) Tell WaypointService to GENERATE voxels from plates tagged WAYPOINT_ZONE_TAG
    --    Configure spacing/size/visuals here (centralized config).
    WaypointService:RegisterProducerTag(WAYPOINT_ZONE_TAG, {
        -- >>> spacing / layout <<<
        partSize       = Vector3.new(1, 1, 1),  -- voxel size
        gap            = 5,                     -- spacing between voxels
        inset          = nil,                   -- default = half partSize; set to custom inner margin if desired
        yOnTopOffset   = 0,                     -- extra Y above plate if needed
        alignToTopFace = true,                  -- keep voxels on top interior layer

        -- visuals
        color          = Color3.fromRGB(255, 170, 0),
        material       = Enum.Material.Plastic,
        transparency   = 0.5,
        anchored       = true,
        canCollide     = false,

        -- output + parenting
        outputTag      = WAYPOINT_PART_TAG,     -- all produced voxels get this tag
        groupFolderName= "WaypointGrids",
        parentStrategy = "siblingFolder",       -- "siblingFolder" | "underProducer" | "underContainer"
    })

    -- 2) Limit queries to THIS grid's waypoint voxels (optional but recommended)
    WaypointService:RegisterIndex(WAYPOINT_PART_TAG, {
        filterAncestor = container,  -- only voxels under this grid
        requireAnchored = true,
    })

    -- 3) Register bridge-top plates as ZonePlus spawn zones for NPC placement
    NPC_SpawnZoneService:RegisterTag(WAYPOINT_ZONE_TAG, {
        autoUpdate = true,
        randomYaw  = false,  -- set true to randomize NPC yaw at spawn
        retries    = 8,      -- helpful for thin/long plates
    })

    return container
end

-- ====== Knit lifecycle ======
function IslandGridService:KnitInit() end

function IslandGridService:KnitStart()
    -- Build one grid by default
    self:SpawnIslandGrid(GRID_ROWS, GRID_COLS, GRID_SPACING, START_CFRAME, workspace)
end

return IslandGridService
