name: LDoc
on: [push, pull_request]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lua and LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 lua5.3-dev luarocks

      - name: Install LDoc
        run: luarocks install ldoc

      - name: Generate docs with LDoc (default)
        run: ldoc src/ReplicatedStorage

      # Uncomment and modify the following step to pass your own arguments
      # - name: Generate docs with LDoc (custom)
      #   run: ldoc src/ReplicatedStorage myfile.lua
