name: LDoc
on: [push, pull_request]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Lua and LuaRocks
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3 lua5.3-dev luarocks

      - name: Install LDoc
        run: luarocks install ldoc --local

      - name: Add local LuaRocks bin to PATH
        run: echo "$(realpath ~/.luarocks/bin)" >> $GITHUB_PATH

      - name: Generate docs with LDoc (default)
        run: ldoc src/ReplicatedStorage -d docs

      - name: Commit and Push documentation
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs
          git commit -m "Update generated documentation"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} main
